FROM amazoncorretto:17-alpine
WORKDIR /back
COPY . .
RUN chmod +x gradlew && mkdir books
CMD ["./gradlew", "clean", "build"]

ENTRYPOINT ["java", "-jar", "build/libs/bangle-0.0.1-SNAPSHOT.jar"]
#ENTRYPOINT ["java", "-jar", "build/libs/Dokkaebi-0.0.1-SNAPSHOT.jar"]