services:
  backend_server:
    container_name: backend_server
    depends_on:
      - backend_kubo
      - backend_redis
      - recommend
    restart: on-failure
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      KUBO_TCP_HOST: backend_kubo:4001
      KUBO_RPC_HOST: backend_kubo:5001
      KUBO_GATEWAY_HOST: backend_kubo:8080
      REDIS_HOST: backend_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DJANGO_URL: http://recommend:8888/api1/string-list/
    volumes:
      - book_volume:/back/books

  backend_kubo:
    container_name: backend_kubo
    image: ipfs/kubo
    volumes:
      - ipfs_data:/data/ipfs
      - ipfs_staging:/export
      - book_volume:/data/books
    ports:
      - "0.0.0.0:4001:4001"  # TCP
      - "127.0.0.1:5001:5001"  # RPC
      - "0.0.0.0:8080:8080"  # Gateway

  backend_redis:
    container_name: backend_redis
    image: redis
    ports:
      - "0.0.0.0:6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_config:/usr/local/etc/redis

  recommend:
    container_name: recommend
    build:
      context: ../recommend
      dockerfile: dockerfile
    ports:
      - "127.0.0.1:8888:8888"

volumes:
  book_volume:
  ipfs_data:
  ipfs_staging:
  redis_config: