export { default as LightImg } from './light.png';
export { default as ShineImg } from './shine.png';
export { default as BannerImg } from './banner.png';
export { default as CartImg } from './cart.png';
export { default as LogoImg } from './logo.png';
export { default as SearchImg } from './search.png';
export { default as BookImg } from './book.png';
export { default as RecommendImg } from './recomend.png';
export { default as CartBlackImg } from './cart_black.png';
